repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: []
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest --cov=loop_bloom --cov-fail-under=80 -q
        language: system
        pass_filenames: false
