[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "loop_bloom"
version = "0.0.1"
description = "ADHD Habit Stacking Tool"
readme = "README.md"
authors = [{name = "Your Name", email = "you@example.com"}]
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["."]
include = ["loop_bloom"]
