storage = "sqlite"
data_path = "/Users/shae/development/loop_bloom/.tmp-test-json/loopbloom.db"
notify = "terminal"
pause_until = "2025-09-20"

[advance]
threshold = 0.8
window = 7
strategy = "ratio"
streak_to_advance = 10

[goal_pauses]
Focus = "2025-09-16"
