name: CI

on:
  pull_request:
    branches: ["*"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run Ruff
        run: poetry run ruff check .
      - name: Check formatting
        run: poetry run black --check .
      - name: Run mypy
        run: poetry run mypy --strict loopbloom
      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=loopbloom --cov-report=xml --cov-fail-under=80
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
      - name: Test install
        run: python -m pip install .
